version: '3.5'
services:
  app1:
    build:
      context: ./app1/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - backend

  app2:
    build:
      context: ./app2/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - backend

  app3:
    build:
      context: ./app3/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - backend

  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./ssl:/usr/local/etc/haproxy/ssl
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
      - app3

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - backend
  #   volumes:
  #     - ./ssl:/etc/nginx/ssl
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - app1
  #     - app2
  #     - app3

networks:
  backend:
