shellcheck:
  image: koalaman/shellcheck-alpine:latest
  stage: test
  before_script:
  - apk update -q; apk add bash -q
  script:
  - bash -e scripts/test/verify.sh

precommit:
  image: alpine
  stage: test
  before_script:
  - apk update && apk add curl git python3 python3-dev gcc g++; \
    apk add --update py-pip; \
    pip install pre-commit
  - git config --global --add safe.directory '*'
  script:
  - pre-commit run --all-files
